trailingComma: 'es5'
tabWidth: 2
singleQuote: true
printWidth: 90
quoteProps: 'preserve'
bracketSpacing: true
arrowParens: 'avoid'
htmlWhitespaceSensitivity: 'ignore'
overrides:
  - files:
      - "*.html"
    options:
      parser: "angular"
