trailingComma: 'es5'
tabWidth: 2
singleQuote: true
printWidth: 100
quoteProps: 'preserve'
bracketSpacing: true
arrowParens: 'avoid'
embeddedLanguageFormatting: 'off'
htmlWhitespaceSensitivity: 'ignore'
overrides:
  - files: "*.html"
    options:
      parser: "angular"
